---EFX Reverb presets
---@module EFX_Presets

---EFX reverb presets (enumeration)
ncine.efx_reverb_presets = {
	GENERIC = 0, ---Default Presets (this and below)
	PADDED_CELL = 1,
	ROOM = 2,
	BATHROOM = 3,
	LIVING_ROOM = 4,
	STONE_ROOM = 5,
	AUDITORIUM = 6,
	CONCERT_HALL = 7,
	CAVE = 8,
	ARENA = 9,
	HANGAR = 10,
	CARPETED_HALLWAY = 11,
	HALLWAY = 12,
	STONE_CORRIDOR = 13,
	ALLEY = 14,
	FOREST = 15,
	CITY = 16,
	MOUNTAINS = 17,
	QUARRY = 18,
	PLAIN = 19,
	PARKING_LOT = 20,
	SEWER_PIPE = 21,
	UNDERWATER = 22,
	DRUGGED = 23,
	DIZZY = 24,
	PSYCHOTIC = 25,

	CASTLE_SMALL_ROOM = 26, ---Castle Presets (this and below)
	CASTLE_SHORT_PASSAGE = 27,
	CASTLE_MEDIUM_ROOM = 28,
	CASTLE_LARGE_ROOM = 29,
	CASTLE_LONG_PASSAGE = 30,
	CASTLE_HALL = 31,
	CASTLE_CUPBOARD = 32,
	CASTLE_COURTYARD = 33,
	CASTLE_ALCOVE = 34,

	FACTORY_SMALL_ROOM = 35, ---Factory Presets (this and below)
	FACTORY_SHORT_PASSAGE = 36,
	FACTORY_MEDIUM_ROOM = 37,
	FACTORY_LARGE_ROOM = 38,
	FACTORY_LONG_PASSAGE = 39,
	FACTORY_HALL = 40,
	FACTORY_CUPBOARD = 41,
	FACTORY_COURTYARD = 42,
	FACTORY_ALCOVE = 43,

	ICEPALACE_SMALL_ROOM = 44, ---Ice Palace Presets (this and below)
	ICEPALACE_SHORT_PASSAGE = 45,
	ICEPALACE_MEDIUM_ROOM = 46,
	ICEPALACE_LARGE_ROOM = 47,
	ICEPALACE_LONG_PASSAGE = 48,
	ICEPALACE_HALL = 49,
	ICEPALACE_CUPBOARD = 50,
	ICEPALACE_COURTYARD = 51,
	ICEPALACE_ALCOVE = 52,

	SPACE_STATION_SMALL_ROOM = 53, ---Space Station Presets (this and below)
	SPACE_STATION_SHORT_PASSAGE = 54,
	SPACE_STATION_MEDIUM_ROOM = 55,
	SPACE_STATION_LARGE_ROOM = 56,
	SPACE_STATION_LONG_PASSAGE = 57,
	SPACE_STATION_HALL = 58,
	SPACE_STATION_CUPBOARD = 59,
	SPACE_STATION_ALCOVE = 60,

	WOODEN_GALLEON_SMALL_ROOM = 61, ---Wooden Galleon Presets (this and below)
	WOODEN_GALLEON_SHORT_PASSAGE = 62,
	WOODEN_GALLEON_MEDIUM_ROOM = 63,
	WOODEN_GALLEON_LARGE_ROOM = 64,
	WOODEN_GALLEON_LONG_PASSAGE = 65,
	WOODEN_GALLEON_HALL = 66,
	WOODEN_GALLEON_CUPBOARD = 67,
	WOODEN_GALLEON_COURTYARD = 68,
	WOODEN_GALLEON_ALCOVE = 69,

	SPORT_EMPTY_STADIUM = 70, ---Sports Presets (this and below)
	SPORT_SQUASH_COURT = 71,
	SPORT_SMALL_SWIMMING_POOL = 72,
	SPORT_LARGE_SWIMMING_POOL = 73,
	SPORT_GYMNASIUM = 74,
	SPORT_FULL_STADIUM = 75,
	SPORT_STADIUM_TANNOY = 76,

	PREFAB_WORKSHOP = 77, ---Prefab Presets (this and below)
	PREFAB_SCHOOL_ROOM = 78,
	PREFAB_PRACTISE_ROOM = 79,
	PREFAB_OUTHOUSE = 80,
	PREFAB_CARAVAN = 81,

	DOME_TOMB = 82, ---Dome and Pipe Presets (this and below)
	PIPE_SMALL = 83,
	DOME_SAINT_PAULS = 84,
	PIPE_LONGTHIN = 85,
	PIPE_LARGE = 86,
	PIPE_RESONANT = 87,

	OUTDOORS_BACKYARD = 88, ---Outdoors Presets (this and below)
	OUTDOORS_ROLLING_PLAINS = 89,
	OUTDOORS_DEEP_CANYON = 90,
	OUTDOORS_CREEK = 91,
	OUTDOORS_VALLEY = 92,

	MOOD_HEAVEN = 93, ---Mood Presets (this and below)
	MOOD_HELL = 94,
	MOOD_MEMORY = 95,

	DRIVING_COMMENTATOR = 96, ---Driving Presets (this and below)
	DRIVING_PIT_GARAGE = 97,
	DRIVING_INCAR_RACER = 98,
	DRIVING_INCAR_SPORTS = 99,
	DRIVING_INCAR_LUXURY = 100,
	DRIVING_FULL_GRANDSTAND = 101,
	DRIVING_EMPTY_GRANDSTAND = 102,
	DRIVING_TUNNEL = 103,

	CITY_STREETS = 104, ---City Presets (this and below)
	CITY_SUBWAY = 105,
	CITY_MUSEUM = 106,
	CITY_LIBRARY = 107,
	CITY_UNDERPASS = 108,
	CITY_ABANDONED = 109,

	DUSTY_ROOM = 110, ---Misc. Presets (this and below)
	CHAPEL = 111,
	SMALL_WATER_ROOM = 112,
}
