name: 'CodeQL'

env:
  LUALS_VERSION: 3.13.0

on: [push, workflow_dispatch]

jobs:
  analyze:
    name: 'Lua Documentation'
    runs-on: 'ubuntu-22.04'

    strategy:
      fail-fast: false

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v4

    - name: 'Download LuaLS'
      run: |
        curl -fsSL https://github.com/LuaLS/lua-language-server/releases/download/$LUALS_VERSION/lua-language-server-$LUALS_VERSION-linux-x64.tar.gz -o lua-language-server-$LUALS_VERSION-linux-x64.tar.gz
        mkdir ../lua-language-server-$LUALS_VERSION-linux-x64
        tar xvpzf lua-language-server-$LUALS_VERSION-linux-x64.tar.gz -C ../lua-language-server-$LUALS_VERSION-linux-x64
        rm lua-language-server-$LUALS_VERSION-linux-x64.tar.gz

    - name: 'Export Documentation with LuaLS'
      run: |
        cd ../lua-language-server-$LUALS_VERSION-linux-x64
        mkdir docs
        ./bin/lua-language-server --loglevel=trace --doc "../nCine-LuaCATS" --doc_out_path "docs"
        mv docs/doc.md ../nCine-LuaCATS/nCine_Lua_API.md

    - name: 'Convert Markdown to HTML'
      uses: ZacJW/markdown-html-action@1.2.0
      with:
        input_files: '[["nCine_Lua_API.md"]]'
        output_files: '["nCine_Lua_API.html"]'

    - name: 'Generate Documentation with LDoc'
      uses: lunarmodules/ldoc@v1.5.0

    - name: 'Push Documentation'
      env:
        PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        export BRANCH_NAME=$(git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD || git rev-parse --short HEAD)

        git clone https://$PUBLIC_REPO_TOKEN@github.com/nCine/docs.git >/dev/null 2>&1
        cd docs

        git rm lua_api_${BRANCH_NAME}.html || true
        cp -p ../nCine_Lua_API.html lua_api_${BRANCH_NAME}.html
        git add lua_api_${BRANCH_NAME}.html

        git rm -r lua_${BRANCH_NAME} || true
        cp -Rp ../doc lua_${BRANCH_NAME}
        git add lua_${BRANCH_NAME}

        git commit --amend -m "Initial commit" || git commit -m "Initial commit"
        git push --force || git push --set-upstream origin master
